# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/albert/.local/lib/python3.10/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/albert/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/albert/Templates/v833_lv9_demos

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/albert/Templates/v833_lv9_demos

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/home/albert/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/albert/.local/lib/python3.10/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/albert/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/albert/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/albert/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/albert/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/albert/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/albert/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/albert/Templates/v833_lv9_demos/CMakeFiles /home/albert/Templates/v833_lv9_demos//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/albert/Templates/v833_lv9_demos/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lua

# Build rule for target.
lua: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lua
.PHONY : lua

# fast build rule for target.
lua/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/build
.PHONY : lua/fast

#=============================================================================
# Target rules for targets named lvgl_linux

# Build rule for target.
lvgl_linux: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lvgl_linux
.PHONY : lvgl_linux

# fast build rule for target.
lvgl_linux/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/build
.PHONY : lvgl_linux/fast

#=============================================================================
# Target rules for targets named lvglsim

# Build rule for target.
lvglsim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lvglsim
.PHONY : lvglsim

# fast build rule for target.
lvglsim/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/build
.PHONY : lvglsim/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

#=============================================================================
# Target rules for targets named clean-all

# Build rule for target.
clean-all: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean-all
.PHONY : clean-all

# fast build rule for target.
clean-all/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clean-all.dir/build.make CMakeFiles/clean-all.dir/build
.PHONY : clean-all/fast

#=============================================================================
# Target rules for targets named lvgl

# Build rule for target.
lvgl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lvgl
.PHONY : lvgl

# fast build rule for target.
lvgl/fast:
	$(MAKE) $(MAKESILENT) -f lvgl/CMakeFiles/lvgl.dir/build.make lvgl/CMakeFiles/lvgl.dir/build
.PHONY : lvgl/fast

#=============================================================================
# Target rules for targets named lv_lib_100ask

# Build rule for target.
lv_lib_100ask: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lv_lib_100ask
.PHONY : lv_lib_100ask

# fast build rule for target.
lv_lib_100ask/fast:
	$(MAKE) $(MAKESILENT) -f src/lib/lv_lib_100ask/CMakeFiles/lv_lib_100ask.dir/build.make src/lib/lv_lib_100ask/CMakeFiles/lv_lib_100ask.dir/build
.PHONY : lv_lib_100ask/fast

src/lib/audio.o: src/lib/audio.c.o
.PHONY : src/lib/audio.o

# target to build an object file
src/lib/audio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/audio.c.o
.PHONY : src/lib/audio.c.o

src/lib/audio.i: src/lib/audio.c.i
.PHONY : src/lib/audio.i

# target to preprocess a source file
src/lib/audio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/audio.c.i
.PHONY : src/lib/audio.c.i

src/lib/audio.s: src/lib/audio.c.s
.PHONY : src/lib/audio.s

# target to generate assembly for a file
src/lib/audio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/audio.c.s
.PHONY : src/lib/audio.c.s

src/lib/button.o: src/lib/button.c.o
.PHONY : src/lib/button.o

# target to build an object file
src/lib/button.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/button.c.o
.PHONY : src/lib/button.c.o

src/lib/button.i: src/lib/button.c.i
.PHONY : src/lib/button.i

# target to preprocess a source file
src/lib/button.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/button.c.i
.PHONY : src/lib/button.c.i

src/lib/button.s: src/lib/button.c.s
.PHONY : src/lib/button.s

# target to generate assembly for a file
src/lib/button.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/button.c.s
.PHONY : src/lib/button.c.s

src/lib/container.o: src/lib/container.c.o
.PHONY : src/lib/container.o

# target to build an object file
src/lib/container.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/container.c.o
.PHONY : src/lib/container.c.o

src/lib/container.i: src/lib/container.c.i
.PHONY : src/lib/container.i

# target to preprocess a source file
src/lib/container.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/container.c.i
.PHONY : src/lib/container.c.i

src/lib/container.s: src/lib/container.c.s
.PHONY : src/lib/container.s

# target to generate assembly for a file
src/lib/container.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/container.c.s
.PHONY : src/lib/container.c.s

src/lib/events.o: src/lib/events.c.o
.PHONY : src/lib/events.o

# target to build an object file
src/lib/events.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/events.c.o
.PHONY : src/lib/events.c.o

src/lib/events.i: src/lib/events.c.i
.PHONY : src/lib/events.i

# target to preprocess a source file
src/lib/events.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/events.c.i
.PHONY : src/lib/events.c.i

src/lib/events.s: src/lib/events.c.s
.PHONY : src/lib/events.s

# target to generate assembly for a file
src/lib/events.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/events.c.s
.PHONY : src/lib/events.c.s

src/lib/file_manager.o: src/lib/file_manager.c.o
.PHONY : src/lib/file_manager.o

# target to build an object file
src/lib/file_manager.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/file_manager.c.o
.PHONY : src/lib/file_manager.c.o

src/lib/file_manager.i: src/lib/file_manager.c.i
.PHONY : src/lib/file_manager.i

# target to preprocess a source file
src/lib/file_manager.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/file_manager.c.i
.PHONY : src/lib/file_manager.c.i

src/lib/file_manager.s: src/lib/file_manager.c.s
.PHONY : src/lib/file_manager.s

# target to generate assembly for a file
src/lib/file_manager.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/file_manager.c.s
.PHONY : src/lib/file_manager.c.s

src/lib/lua/lapi.o: src/lib/lua/lapi.c.o
.PHONY : src/lib/lua/lapi.o

# target to build an object file
src/lib/lua/lapi.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/lapi.c.o
.PHONY : src/lib/lua/lapi.c.o

src/lib/lua/lapi.i: src/lib/lua/lapi.c.i
.PHONY : src/lib/lua/lapi.i

# target to preprocess a source file
src/lib/lua/lapi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/lapi.c.i
.PHONY : src/lib/lua/lapi.c.i

src/lib/lua/lapi.s: src/lib/lua/lapi.c.s
.PHONY : src/lib/lua/lapi.s

# target to generate assembly for a file
src/lib/lua/lapi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/lapi.c.s
.PHONY : src/lib/lua/lapi.c.s

src/lib/lua/lauxlib.o: src/lib/lua/lauxlib.c.o
.PHONY : src/lib/lua/lauxlib.o

# target to build an object file
src/lib/lua/lauxlib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/lauxlib.c.o
.PHONY : src/lib/lua/lauxlib.c.o

src/lib/lua/lauxlib.i: src/lib/lua/lauxlib.c.i
.PHONY : src/lib/lua/lauxlib.i

# target to preprocess a source file
src/lib/lua/lauxlib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/lauxlib.c.i
.PHONY : src/lib/lua/lauxlib.c.i

src/lib/lua/lauxlib.s: src/lib/lua/lauxlib.c.s
.PHONY : src/lib/lua/lauxlib.s

# target to generate assembly for a file
src/lib/lua/lauxlib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/lauxlib.c.s
.PHONY : src/lib/lua/lauxlib.c.s

src/lib/lua/lbaselib.o: src/lib/lua/lbaselib.c.o
.PHONY : src/lib/lua/lbaselib.o

# target to build an object file
src/lib/lua/lbaselib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/lbaselib.c.o
.PHONY : src/lib/lua/lbaselib.c.o

src/lib/lua/lbaselib.i: src/lib/lua/lbaselib.c.i
.PHONY : src/lib/lua/lbaselib.i

# target to preprocess a source file
src/lib/lua/lbaselib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/lbaselib.c.i
.PHONY : src/lib/lua/lbaselib.c.i

src/lib/lua/lbaselib.s: src/lib/lua/lbaselib.c.s
.PHONY : src/lib/lua/lbaselib.s

# target to generate assembly for a file
src/lib/lua/lbaselib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/lbaselib.c.s
.PHONY : src/lib/lua/lbaselib.c.s

src/lib/lua/lfunc.o: src/lib/lua/lfunc.c.o
.PHONY : src/lib/lua/lfunc.o

# target to build an object file
src/lib/lua/lfunc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/lfunc.c.o
.PHONY : src/lib/lua/lfunc.c.o

src/lib/lua/lfunc.i: src/lib/lua/lfunc.c.i
.PHONY : src/lib/lua/lfunc.i

# target to preprocess a source file
src/lib/lua/lfunc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/lfunc.c.i
.PHONY : src/lib/lua/lfunc.c.i

src/lib/lua/lfunc.s: src/lib/lua/lfunc.c.s
.PHONY : src/lib/lua/lfunc.s

# target to generate assembly for a file
src/lib/lua/lfunc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/lfunc.c.s
.PHONY : src/lib/lua/lfunc.c.s

src/lib/lua/linit.o: src/lib/lua/linit.c.o
.PHONY : src/lib/lua/linit.o

# target to build an object file
src/lib/lua/linit.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/linit.c.o
.PHONY : src/lib/lua/linit.c.o

src/lib/lua/linit.i: src/lib/lua/linit.c.i
.PHONY : src/lib/lua/linit.i

# target to preprocess a source file
src/lib/lua/linit.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/linit.c.i
.PHONY : src/lib/lua/linit.c.i

src/lib/lua/linit.s: src/lib/lua/linit.c.s
.PHONY : src/lib/lua/linit.s

# target to generate assembly for a file
src/lib/lua/linit.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/linit.c.s
.PHONY : src/lib/lua/linit.c.s

src/lib/lua/liolib.o: src/lib/lua/liolib.c.o
.PHONY : src/lib/lua/liolib.o

# target to build an object file
src/lib/lua/liolib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/liolib.c.o
.PHONY : src/lib/lua/liolib.c.o

src/lib/lua/liolib.i: src/lib/lua/liolib.c.i
.PHONY : src/lib/lua/liolib.i

# target to preprocess a source file
src/lib/lua/liolib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/liolib.c.i
.PHONY : src/lib/lua/liolib.c.i

src/lib/lua/liolib.s: src/lib/lua/liolib.c.s
.PHONY : src/lib/lua/liolib.s

# target to generate assembly for a file
src/lib/lua/liolib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/liolib.c.s
.PHONY : src/lib/lua/liolib.c.s

src/lib/lua/lmathlib.o: src/lib/lua/lmathlib.c.o
.PHONY : src/lib/lua/lmathlib.o

# target to build an object file
src/lib/lua/lmathlib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/lmathlib.c.o
.PHONY : src/lib/lua/lmathlib.c.o

src/lib/lua/lmathlib.i: src/lib/lua/lmathlib.c.i
.PHONY : src/lib/lua/lmathlib.i

# target to preprocess a source file
src/lib/lua/lmathlib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/lmathlib.c.i
.PHONY : src/lib/lua/lmathlib.c.i

src/lib/lua/lmathlib.s: src/lib/lua/lmathlib.c.s
.PHONY : src/lib/lua/lmathlib.s

# target to generate assembly for a file
src/lib/lua/lmathlib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/lmathlib.c.s
.PHONY : src/lib/lua/lmathlib.c.s

src/lib/lua/loslib.o: src/lib/lua/loslib.c.o
.PHONY : src/lib/lua/loslib.o

# target to build an object file
src/lib/lua/loslib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/loslib.c.o
.PHONY : src/lib/lua/loslib.c.o

src/lib/lua/loslib.i: src/lib/lua/loslib.c.i
.PHONY : src/lib/lua/loslib.i

# target to preprocess a source file
src/lib/lua/loslib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/loslib.c.i
.PHONY : src/lib/lua/loslib.c.i

src/lib/lua/loslib.s: src/lib/lua/loslib.c.s
.PHONY : src/lib/lua/loslib.s

# target to generate assembly for a file
src/lib/lua/loslib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/loslib.c.s
.PHONY : src/lib/lua/loslib.c.s

src/lib/lua/lstate.o: src/lib/lua/lstate.c.o
.PHONY : src/lib/lua/lstate.o

# target to build an object file
src/lib/lua/lstate.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/lstate.c.o
.PHONY : src/lib/lua/lstate.c.o

src/lib/lua/lstate.i: src/lib/lua/lstate.c.i
.PHONY : src/lib/lua/lstate.i

# target to preprocess a source file
src/lib/lua/lstate.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/lstate.c.i
.PHONY : src/lib/lua/lstate.c.i

src/lib/lua/lstate.s: src/lib/lua/lstate.c.s
.PHONY : src/lib/lua/lstate.s

# target to generate assembly for a file
src/lib/lua/lstate.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/lstate.c.s
.PHONY : src/lib/lua/lstate.c.s

src/lib/lua/lstring.o: src/lib/lua/lstring.c.o
.PHONY : src/lib/lua/lstring.o

# target to build an object file
src/lib/lua/lstring.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/lstring.c.o
.PHONY : src/lib/lua/lstring.c.o

src/lib/lua/lstring.i: src/lib/lua/lstring.c.i
.PHONY : src/lib/lua/lstring.i

# target to preprocess a source file
src/lib/lua/lstring.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/lstring.c.i
.PHONY : src/lib/lua/lstring.c.i

src/lib/lua/lstring.s: src/lib/lua/lstring.c.s
.PHONY : src/lib/lua/lstring.s

# target to generate assembly for a file
src/lib/lua/lstring.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/lstring.c.s
.PHONY : src/lib/lua/lstring.c.s

src/lib/lua/lstrlib.o: src/lib/lua/lstrlib.c.o
.PHONY : src/lib/lua/lstrlib.o

# target to build an object file
src/lib/lua/lstrlib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/lstrlib.c.o
.PHONY : src/lib/lua/lstrlib.c.o

src/lib/lua/lstrlib.i: src/lib/lua/lstrlib.c.i
.PHONY : src/lib/lua/lstrlib.i

# target to preprocess a source file
src/lib/lua/lstrlib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/lstrlib.c.i
.PHONY : src/lib/lua/lstrlib.c.i

src/lib/lua/lstrlib.s: src/lib/lua/lstrlib.c.s
.PHONY : src/lib/lua/lstrlib.s

# target to generate assembly for a file
src/lib/lua/lstrlib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/lstrlib.c.s
.PHONY : src/lib/lua/lstrlib.c.s

src/lib/lua/ltable.o: src/lib/lua/ltable.c.o
.PHONY : src/lib/lua/ltable.o

# target to build an object file
src/lib/lua/ltable.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/ltable.c.o
.PHONY : src/lib/lua/ltable.c.o

src/lib/lua/ltable.i: src/lib/lua/ltable.c.i
.PHONY : src/lib/lua/ltable.i

# target to preprocess a source file
src/lib/lua/ltable.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/ltable.c.i
.PHONY : src/lib/lua/ltable.c.i

src/lib/lua/ltable.s: src/lib/lua/ltable.c.s
.PHONY : src/lib/lua/ltable.s

# target to generate assembly for a file
src/lib/lua/ltable.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/ltable.c.s
.PHONY : src/lib/lua/ltable.c.s

src/lib/lua/lutf8lib.o: src/lib/lua/lutf8lib.c.o
.PHONY : src/lib/lua/lutf8lib.o

# target to build an object file
src/lib/lua/lutf8lib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/lutf8lib.c.o
.PHONY : src/lib/lua/lutf8lib.c.o

src/lib/lua/lutf8lib.i: src/lib/lua/lutf8lib.c.i
.PHONY : src/lib/lua/lutf8lib.i

# target to preprocess a source file
src/lib/lua/lutf8lib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/lutf8lib.c.i
.PHONY : src/lib/lua/lutf8lib.c.i

src/lib/lua/lutf8lib.s: src/lib/lua/lutf8lib.c.s
.PHONY : src/lib/lua/lutf8lib.s

# target to generate assembly for a file
src/lib/lua/lutf8lib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/lutf8lib.c.s
.PHONY : src/lib/lua/lutf8lib.c.s

src/lib/lua/lvm.o: src/lib/lua/lvm.c.o
.PHONY : src/lib/lua/lvm.o

# target to build an object file
src/lib/lua/lvm.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/lvm.c.o
.PHONY : src/lib/lua/lvm.c.o

src/lib/lua/lvm.i: src/lib/lua/lvm.c.i
.PHONY : src/lib/lua/lvm.i

# target to preprocess a source file
src/lib/lua/lvm.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/lvm.c.i
.PHONY : src/lib/lua/lvm.c.i

src/lib/lua/lvm.s: src/lib/lua/lvm.c.s
.PHONY : src/lib/lua/lvm.s

# target to generate assembly for a file
src/lib/lua/lvm.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua.dir/build.make CMakeFiles/lua.dir/src/lib/lua/lvm.c.s
.PHONY : src/lib/lua/lvm.c.s

src/lib/player.o: src/lib/player.c.o
.PHONY : src/lib/player.o

# target to build an object file
src/lib/player.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/player.c.o
.PHONY : src/lib/player.c.o

src/lib/player.i: src/lib/player.c.i
.PHONY : src/lib/player.i

# target to preprocess a source file
src/lib/player.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/player.c.i
.PHONY : src/lib/player.c.i

src/lib/player.s: src/lib/player.c.s
.PHONY : src/lib/player.s

# target to generate assembly for a file
src/lib/player.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/player.c.s
.PHONY : src/lib/player.c.s

src/lib/settings.o: src/lib/settings.c.o
.PHONY : src/lib/settings.o

# target to build an object file
src/lib/settings.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/settings.c.o
.PHONY : src/lib/settings.c.o

src/lib/settings.i: src/lib/settings.c.i
.PHONY : src/lib/settings.i

# target to preprocess a source file
src/lib/settings.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/settings.c.i
.PHONY : src/lib/settings.c.i

src/lib/settings.s: src/lib/settings.c.s
.PHONY : src/lib/settings.s

# target to generate assembly for a file
src/lib/settings.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/settings.c.s
.PHONY : src/lib/settings.c.s

src/lib/virsual_novel/cJSON.o: src/lib/virsual_novel/cJSON.c.o
.PHONY : src/lib/virsual_novel/cJSON.o

# target to build an object file
src/lib/virsual_novel/cJSON.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/virsual_novel/cJSON.c.o
.PHONY : src/lib/virsual_novel/cJSON.c.o

src/lib/virsual_novel/cJSON.i: src/lib/virsual_novel/cJSON.c.i
.PHONY : src/lib/virsual_novel/cJSON.i

# target to preprocess a source file
src/lib/virsual_novel/cJSON.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/virsual_novel/cJSON.c.i
.PHONY : src/lib/virsual_novel/cJSON.c.i

src/lib/virsual_novel/cJSON.s: src/lib/virsual_novel/cJSON.c.s
.PHONY : src/lib/virsual_novel/cJSON.s

# target to generate assembly for a file
src/lib/virsual_novel/cJSON.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/virsual_novel/cJSON.c.s
.PHONY : src/lib/virsual_novel/cJSON.c.s

src/lib/virsual_novel/data_parser.o: src/lib/virsual_novel/data_parser.c.o
.PHONY : src/lib/virsual_novel/data_parser.o

# target to build an object file
src/lib/virsual_novel/data_parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/virsual_novel/data_parser.c.o
.PHONY : src/lib/virsual_novel/data_parser.c.o

src/lib/virsual_novel/data_parser.i: src/lib/virsual_novel/data_parser.c.i
.PHONY : src/lib/virsual_novel/data_parser.i

# target to preprocess a source file
src/lib/virsual_novel/data_parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/virsual_novel/data_parser.c.i
.PHONY : src/lib/virsual_novel/data_parser.c.i

src/lib/virsual_novel/data_parser.s: src/lib/virsual_novel/data_parser.c.s
.PHONY : src/lib/virsual_novel/data_parser.s

# target to generate assembly for a file
src/lib/virsual_novel/data_parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/virsual_novel/data_parser.c.s
.PHONY : src/lib/virsual_novel/data_parser.c.s

src/lib/virsual_novel/resource_manager.o: src/lib/virsual_novel/resource_manager.c.o
.PHONY : src/lib/virsual_novel/resource_manager.o

# target to build an object file
src/lib/virsual_novel/resource_manager.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/virsual_novel/resource_manager.c.o
.PHONY : src/lib/virsual_novel/resource_manager.c.o

src/lib/virsual_novel/resource_manager.i: src/lib/virsual_novel/resource_manager.c.i
.PHONY : src/lib/virsual_novel/resource_manager.i

# target to preprocess a source file
src/lib/virsual_novel/resource_manager.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/virsual_novel/resource_manager.c.i
.PHONY : src/lib/virsual_novel/resource_manager.c.i

src/lib/virsual_novel/resource_manager.s: src/lib/virsual_novel/resource_manager.c.s
.PHONY : src/lib/virsual_novel/resource_manager.s

# target to generate assembly for a file
src/lib/virsual_novel/resource_manager.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/virsual_novel/resource_manager.c.s
.PHONY : src/lib/virsual_novel/resource_manager.c.s

src/lib/virsual_novel/simple_json.o: src/lib/virsual_novel/simple_json.c.o
.PHONY : src/lib/virsual_novel/simple_json.o

# target to build an object file
src/lib/virsual_novel/simple_json.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/virsual_novel/simple_json.c.o
.PHONY : src/lib/virsual_novel/simple_json.c.o

src/lib/virsual_novel/simple_json.i: src/lib/virsual_novel/simple_json.c.i
.PHONY : src/lib/virsual_novel/simple_json.i

# target to preprocess a source file
src/lib/virsual_novel/simple_json.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/virsual_novel/simple_json.c.i
.PHONY : src/lib/virsual_novel/simple_json.c.i

src/lib/virsual_novel/simple_json.s: src/lib/virsual_novel/simple_json.c.s
.PHONY : src/lib/virsual_novel/simple_json.s

# target to generate assembly for a file
src/lib/virsual_novel/simple_json.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/virsual_novel/simple_json.c.s
.PHONY : src/lib/virsual_novel/simple_json.c.s

src/lib/virsual_novel/visual_novel_engine.o: src/lib/virsual_novel/visual_novel_engine.c.o
.PHONY : src/lib/virsual_novel/visual_novel_engine.o

# target to build an object file
src/lib/virsual_novel/visual_novel_engine.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/virsual_novel/visual_novel_engine.c.o
.PHONY : src/lib/virsual_novel/visual_novel_engine.c.o

src/lib/virsual_novel/visual_novel_engine.i: src/lib/virsual_novel/visual_novel_engine.c.i
.PHONY : src/lib/virsual_novel/visual_novel_engine.i

# target to preprocess a source file
src/lib/virsual_novel/visual_novel_engine.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/virsual_novel/visual_novel_engine.c.i
.PHONY : src/lib/virsual_novel/visual_novel_engine.c.i

src/lib/virsual_novel/visual_novel_engine.s: src/lib/virsual_novel/visual_novel_engine.c.s
.PHONY : src/lib/virsual_novel/visual_novel_engine.s

# target to generate assembly for a file
src/lib/virsual_novel/visual_novel_engine.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvgl_linux.dir/build.make CMakeFiles/lvgl_linux.dir/src/lib/virsual_novel/visual_novel_engine.c.s
.PHONY : src/lib/virsual_novel/visual_novel_engine.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lvglsim.dir/build.make CMakeFiles/lvglsim.dir/src/main.c.s
.PHONY : src/main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... clean-all"
	@echo "... run"
	@echo "... lua"
	@echo "... lv_lib_100ask"
	@echo "... lvgl"
	@echo "... lvgl_linux"
	@echo "... lvglsim"
	@echo "... src/lib/audio.o"
	@echo "... src/lib/audio.i"
	@echo "... src/lib/audio.s"
	@echo "... src/lib/button.o"
	@echo "... src/lib/button.i"
	@echo "... src/lib/button.s"
	@echo "... src/lib/container.o"
	@echo "... src/lib/container.i"
	@echo "... src/lib/container.s"
	@echo "... src/lib/events.o"
	@echo "... src/lib/events.i"
	@echo "... src/lib/events.s"
	@echo "... src/lib/file_manager.o"
	@echo "... src/lib/file_manager.i"
	@echo "... src/lib/file_manager.s"
	@echo "... src/lib/lua/lapi.o"
	@echo "... src/lib/lua/lapi.i"
	@echo "... src/lib/lua/lapi.s"
	@echo "... src/lib/lua/lauxlib.o"
	@echo "... src/lib/lua/lauxlib.i"
	@echo "... src/lib/lua/lauxlib.s"
	@echo "... src/lib/lua/lbaselib.o"
	@echo "... src/lib/lua/lbaselib.i"
	@echo "... src/lib/lua/lbaselib.s"
	@echo "... src/lib/lua/lfunc.o"
	@echo "... src/lib/lua/lfunc.i"
	@echo "... src/lib/lua/lfunc.s"
	@echo "... src/lib/lua/linit.o"
	@echo "... src/lib/lua/linit.i"
	@echo "... src/lib/lua/linit.s"
	@echo "... src/lib/lua/liolib.o"
	@echo "... src/lib/lua/liolib.i"
	@echo "... src/lib/lua/liolib.s"
	@echo "... src/lib/lua/lmathlib.o"
	@echo "... src/lib/lua/lmathlib.i"
	@echo "... src/lib/lua/lmathlib.s"
	@echo "... src/lib/lua/loslib.o"
	@echo "... src/lib/lua/loslib.i"
	@echo "... src/lib/lua/loslib.s"
	@echo "... src/lib/lua/lstate.o"
	@echo "... src/lib/lua/lstate.i"
	@echo "... src/lib/lua/lstate.s"
	@echo "... src/lib/lua/lstring.o"
	@echo "... src/lib/lua/lstring.i"
	@echo "... src/lib/lua/lstring.s"
	@echo "... src/lib/lua/lstrlib.o"
	@echo "... src/lib/lua/lstrlib.i"
	@echo "... src/lib/lua/lstrlib.s"
	@echo "... src/lib/lua/ltable.o"
	@echo "... src/lib/lua/ltable.i"
	@echo "... src/lib/lua/ltable.s"
	@echo "... src/lib/lua/lutf8lib.o"
	@echo "... src/lib/lua/lutf8lib.i"
	@echo "... src/lib/lua/lutf8lib.s"
	@echo "... src/lib/lua/lvm.o"
	@echo "... src/lib/lua/lvm.i"
	@echo "... src/lib/lua/lvm.s"
	@echo "... src/lib/player.o"
	@echo "... src/lib/player.i"
	@echo "... src/lib/player.s"
	@echo "... src/lib/settings.o"
	@echo "... src/lib/settings.i"
	@echo "... src/lib/settings.s"
	@echo "... src/lib/virsual_novel/cJSON.o"
	@echo "... src/lib/virsual_novel/cJSON.i"
	@echo "... src/lib/virsual_novel/cJSON.s"
	@echo "... src/lib/virsual_novel/data_parser.o"
	@echo "... src/lib/virsual_novel/data_parser.i"
	@echo "... src/lib/virsual_novel/data_parser.s"
	@echo "... src/lib/virsual_novel/resource_manager.o"
	@echo "... src/lib/virsual_novel/resource_manager.i"
	@echo "... src/lib/virsual_novel/resource_manager.s"
	@echo "... src/lib/virsual_novel/simple_json.o"
	@echo "... src/lib/virsual_novel/simple_json.i"
	@echo "... src/lib/virsual_novel/simple_json.s"
	@echo "... src/lib/virsual_novel/visual_novel_engine.o"
	@echo "... src/lib/virsual_novel/visual_novel_engine.i"
	@echo "... src/lib/virsual_novel/visual_novel_engine.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

