#!/bin/sh

cd /mnt/app

if cat /mnt/app/robot_select.txt | grep robot_run_1; then
    echo "run robot_run_1"
    #chmod 777 ./robot_run_1
    killall -SIGCONT robot_run_1 &
else
    echo "run robot_run"
    #chmod 777 ./robot_run
    killall -SIGCONT robot_run &
fi
